<?php

namespace ContainerXV74Jex;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Core_Grid_Definition_Factory_Monitoring_ProductWithoutImageService extends AdminKernelProdContainer
{
    /*
     * Gets the public '.container.private.prestashop.core.grid.definition.factory.monitoring.product_without_image' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\ProductWithoutImageGridDefinitionFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['.container.private.prestashop.core.grid.definition.factory.monitoring.product_without_image'] = $instance = new \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\ProductWithoutImageGridDefinitionFactory(($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)));

        $instance->setTranslator(($container->services['translator'] ?? self::getTranslatorService($container)));

        return $instance;
    }
}
