<?php

namespace ContainerXV74Jex;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrierRangesTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Improve\Shipping\Carrier\Type\CarrierRangesType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Improve\Shipping\Carrier\Type\CarrierRangesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Improve\\Shipping\\Carrier\\Type\\CarrierRangesType'] = new \PrestaShopBundle\Form\Admin\Improve\Shipping\Carrier\Type\CarrierRangesType(($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(false));
    }
}
