<?php

namespace ContainerXV74Jex;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalizationControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Improve\International\LocalizationController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Improve\International\LocalizationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Improve\\International\\LocalizationController'] = $instance = new \PrestaShopBundle\Controller\Admin\Improve\International\LocalizationController();

        $instance->setContainer(($container->privates['.service_locator.UCPHT9s'] ?? $container->load('get_ServiceLocator_UCPHT9sService'))->withContext('PrestaShopBundle\\Controller\\Admin\\Improve\\International\\LocalizationController', $container));

        return $instance;
    }
}
