<?php

namespace ContainerW1lD7Dh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityController2Service extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\SecurityController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\SecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\SecurityController'] = $instance = new \PrestaShopBundle\Controller\Admin\SecurityController(($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)), ($container->services['Symfony\\Component\\Security\\Csrf\\CsrfTokenManagerInterface'] ?? self::getCsrfTokenManagerInterfaceService($container)), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService')));

        $instance->setContainer(($container->privates['.service_locator.UCPHT9s'] ?? $container->load('get_ServiceLocator_UCPHT9sService'))->withContext('PrestaShopBundle\\Controller\\Admin\\SecurityController', $container));

        return $instance;
    }
}
