<?php

namespace ContainerDYEZbFM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesProviderService extends AdminKernelProdDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Service\DataProvider\Admin\CategoriesProvider' shared service.
     *
     * @return \PrestaShopBundle\Service\DataProvider\Admin\CategoriesProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['PrestaShopBundle\\Service\\DataProvider\\Admin\\CategoriesProvider'] = $container->createProxy('CategoriesProviderProxyEc40e6e', static fn () => \CategoriesProviderProxyEc40e6e::createLazyProxy(static fn () => self::do($container, false)));
        }

        return ($container->services['PrestaShop\\PrestaShop\\Adapter\\Category\\CategoriesProviderBuilder'] ?? $container->load('getCategoriesProviderBuilderService'))->build();
    }
}
