<?php

namespace ContainerDYEZbFM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContextBuilderPreparerService extends AdminKernelProdDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Core\Context\ContextBuilderPreparer' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Context\ContextBuilderPreparer
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['PrestaShop\\PrestaShop\\Core\\Context\\ContextBuilderPreparer'] = $container->createProxy('ContextBuilderPreparerGhost2c02a61', static fn () => \ContextBuilderPreparerGhost2c02a61::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        return ($lazyLoad->__construct(($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContextBuilder'] ?? self::getLanguageContextBuilderService($container))) && false ?: $lazyLoad);
    }
}
