<?php

namespace ContainerDYEZbFM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCacheWarmerService extends AdminKernelProdDebugContainer
{
    /**
     * Gets the public 'cache_warmer' shared service.
     *
     * @return \Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['cache_warmer'] = new \Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['api_platform.cache_warmer.cache_pool_clearer'] ?? $container->load('getApiPlatform_CacheWarmer_CachePoolClearerService'));
            yield 1 => ($container->privates['config_builder.warmer'] ?? $container->load('getConfigBuilder_WarmerService'));
            yield 2 => ($container->privates['translation.warmer'] ?? $container->load('getTranslation_WarmerService'));
            yield 3 => ($container->privates['router.cache_warmer'] ?? $container->load('getRouter_CacheWarmerService'));
            yield 4 => ($container->privates['annotations.cache_warmer'] ?? $container->load('getAnnotations_CacheWarmerService'));
            yield 5 => ($container->privates['serializer.mapping.cache_warmer'] ?? $container->load('getSerializer_Mapping_CacheWarmerService'));
            yield 6 => ($container->privates['validator.mapping.cache_warmer'] ?? $container->load('getValidator_Mapping_CacheWarmerService'));
            yield 7 => ($container->privates['security.cache_warmer.expression'] ?? $container->load('getSecurity_CacheWarmer_ExpressionService'));
            yield 8 => ($container->privates['twig.template_cache_warmer'] ?? $container->load('getTwig_TemplateCacheWarmerService'));
            yield 9 => ($container->privates['doctrine.orm.proxy_cache_warmer'] ?? $container->load('getDoctrine_Orm_ProxyCacheWarmerService'));
            yield 10 => ($container->services['main.warmer.cache_warmer'] ?? $container->load('getMain_Warmer_CacheWarmerService'));
            yield 11 => ($container->privates['PrestaShopBundle\\Routing\\AnonymousRouteProvider'] ?? $container->load('getAnonymousRouteProviderService'));
            yield 12 => ($container->privates['ux.twig_component.cache_warmer'] ?? $container->load('getUx_TwigComponent_CacheWarmerService'));
        }, 13), true, ($container->targetDir.''.'/AdminKernelProdDebugContainerDeprecations.log'));
    }
}
