<?php

namespace ContainerDYEZbFM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeePasswordResetterService extends AdminKernelProdDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Security\Admin\EmployeePasswordResetter' shared autowired service.
     *
     * @return \PrestaShopBundle\Security\Admin\EmployeePasswordResetter
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['PrestaShopBundle\\Security\\Admin\\EmployeePasswordResetter'] = $container->createProxy('EmployeePasswordResetterGhost29bcb85', static fn () => \EmployeePasswordResetterGhost29bcb85::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        return ($lazyLoad->__construct(($container->services['PrestaShopBundle\\Entity\\Repository\\EmployeeRepository'] ?? self::getEmployeeRepositoryService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService')), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContext2Service($container)), ($container->services['hashing'] ??= new \PrestaShop\PrestaShop\Core\Crypto\Hashing()), 'XbCWdiUv6r0dfTUZTGgiwNP5b8HRcnIL9pqE64b08hbvdO0FUSEZPIsFXfB9yHhu') && false ?: $lazyLoad);
    }
}
