<?php

namespace ContainerDYEZbFM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportDataConfigurationControllerService extends AdminKernelProdDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\ImportDataConfigurationController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\ImportDataConfigurationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\ImportDataConfigurationController'] = $instance = new \PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\ImportDataConfigurationController();

        $instance->setContainer(($container->privates['.service_locator.UCPHT9s'] ?? $container->load('get_ServiceLocator_UCPHT9sService'))->withContext('PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\ImportDataConfigurationController', $container));

        return $instance;
    }
}
