<?php

namespace ContainerDYEZbFM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryLayerService extends AdminKernelProdDebugContainer
{
    /**
     * Gets the private 'PrestaShop\PrestaShop\Core\FeatureFlag\Layer\QueryLayer' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\FeatureFlag\Layer\QueryLayer
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['PrestaShop\\PrestaShop\\Core\\FeatureFlag\\Layer\\QueryLayer'] = $container->createProxy('QueryLayerGhost529273f', static fn () => \QueryLayerGhost529273f::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        return ($lazyLoad->__construct(($container->services['prestashop.adapter.environment'] ??= new \PrestaShop\PrestaShop\Adapter\Environment(true, 'prod', 'admin')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: $lazyLoad);
    }
}
