<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXV74Jex\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXV74Jex/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXV74Jex.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerXV74Jex\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerXV74Jex\AdminKernelProdContainer([
    'container.build_hash' => 'XV74Jex',
    'container.build_id' => '9822f570',
    'container.build_time' => 1771706894,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXV74Jex');
