<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDYEZbFM\AdminKernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDYEZbFM/AdminKernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerDYEZbFM.legacy');

    return;
}

if (!\class_exists(AdminKernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerDYEZbFM\AdminKernelProdDebugContainer::class, AdminKernelProdDebugContainer::class, false);
}

return new \ContainerDYEZbFM\AdminKernelProdDebugContainer([
    'container.build_hash' => 'DYEZbFM',
    'container.build_id' => 'e09e1cff',
    'container.build_time' => 1771706900,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDYEZbFM');
